CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(64) NOT NULL DEFAULT '',
    password VARCHAR(64) NOT NULL DEFAULT '',
    email VARCHAR(256) NOT NULL DEFAULT '',
    phone VARCHAR(16) NOT NULL DEFAULT '',
    role TEXT CHECK ( role IN ('admin', 'student') ),
    surname VARCHAR(64) NOT NULL DEFAULT ''
);

CREATE TABLE kazan_unis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL DEFAULT '',
    short_name VARCHAR(64) NOT NULL DEFAULT '',
    img1 VARCHAR(256) NOT NULL DEFAULT '',
    img2 VARCHAR(256) NOT NULL DEFAULT '',
    article1 VARCHAR(512) NOT NULL DEFAULT '',
    article2 VARCHAR(512) NOT NULL DEFAULT '',
    url VARCHAR(256) NOT NULL DEFAULT ''
);

CREATE TABLE moscow_unis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL DEFAULT '',
    short_name VARCHAR(64) NOT NULL DEFAULT '',
    img1 VARCHAR(256) NOT NULL DEFAULT '',
    img2 VARCHAR(256) NOT NULL DEFAULT '',
    article1 VARCHAR(512) NOT NULL DEFAULT '',
    article2 VARCHAR(512) NOT NULL DEFAULT '',
    url VARCHAR(256) NOT NULL DEFAULT ''
);

CREATE TABLE stp_unis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL DEFAULT '',
    short_name VARCHAR(64) NOT NULL DEFAULT '',
    img1 VARCHAR(256) NOT NULL DEFAULT '',
    img2 VARCHAR(256) NOT NULL DEFAULT '',
    article1 VARCHAR(512) NOT NULL DEFAULT '',
    article2 VARCHAR(512) NOT NULL DEFAULT '',
    url VARCHAR(256) NOT NULL DEFAULT ''
);

INSERT INTO kazan_unis (name, short_name, img1, img2, article1, article2, url) 
VALUES 
('Казанский (Приволжский) федеральный университет',
 'К(П)ФУ',
 'https://prepschool.kpfu.ru/content/uploads/2020/12/untitled-5-of-8-scaled.jpg',
 'https://kpfu.ru/portal/docs/F182267925/kfu_finansovyj.jpg',
 'Основан в 1804 году как Императорский Казанский университет. Включает 18 институтов, 3 филиала и 300+ образовательных программ. В топ-5 вузов России по научным исследованиям.', 
 'Крупнейший вуз Татарстана с 50 тыс. студентов. Кампус включает ботанический сад, музеи и лаборатории. Партнёр 130+ зарубежных университетов.',
 'https://admissions.kpfu.ru'),
('Казанский национальный исследовательский технический университет им. А.Н. Туполева - КАИ',
 'КНИТУ КАИ',
 'https://licey20ul.gosuslugi.ru/netcat_files/146/2690/694.jpg',
 'https://happylove.top/uploads/posts/2023-09/1694584275_happylove-top-p-kazan-universitet-foto-krasivo-16.jpg',
 'Ведущий аэрокосмический вуз России с 1932 года. Готовит инженеров для авиации, IT и робототехники. Имеет собственный аэродром и центр 3D-печати.', 
 'Разрабатывает двигатели для беспилотников и спутников. 85% выпускников трудоустраиваются в Роскосмос, Boeing и IT-компании.',
 'https://www.abiturientu.kai.ru'),
('Казанский государственный медицинский университет',
 'КГМУ',
 'https://entermedia.io/wp-content/uploads/2023/10/2-Zdanie-Medinstituta.jpg',
 'https://i.vuzopedia.ru/storage/app/uploads/public/5a3/274/069/5a3274069854a434144164.jpg',
 'Основан в 1814 году. В топ-5 медвузов страны. Готовит врачей 50+ специальностей, включая нейрохирургию и генетику. Клиническая база — 20+ больниц.', 
 'Пионер в телемедицине: проводит онлайн-консультации для 30 регионов. Разработал 100+ медицинских методик.',
 'https://kazangmu.ru/abitur'),
('Казанский национальный исследовательский технологический университет',
 'КНИТУ',
 'https://www.kstu.ru/servlet/contentblob?id=424',
 'https://avatars.mds.yandex.net/i?id=154b996fdda24d25bdfd2c72a816e7c4_l-5246115-images-thumbs&n=13',
 'Лидер в химии и нефтепереработке с 1890 года. 15 патентов ежегодно. Лаборатории оснащены VR-тренажёрами для химиков.', 
 'Сотрудничает с «Татнефтью» и BASF. Студенты проходят практику на современных нефтезаводах.',
 'https://www.kstu.ru/Abitur/'),
('Казанский государственный энергетический университет',
 'КГЭУ',
 'https://old.kgeu.ru/News/GetImage/11812',
 'https://ojm.tatarstan.ru/file/news/1981_n2212910_big.jpg',
 'Готовит инженеров для smart-сетей и ВИЭ с 1968 года. Имеет ветрогенератор и солнечные панели на кампусе.', 
 'Разрабатывает энергосберегающие технологии. 90% выпускников работают в «Россети» и «Газпром энерго».',
 'https://kgeu.ru/abiturentu/'),
('Казанский государственный архитектурно-строительный университет',
 'КГАСУ',
 'https://sys3.ru/gof-marketplace/uploads/organizations/preview/PQpdozt4fYq10b2bwW5WbLXAzTdBwtk4qUa2Is98.jpg',
 'https://realnoevremya.ru/uploads/gallery/bb/8d/ea8b34c529e91d85.jpg',
 'Ведущий строительный вуз Поволжья с 1930 года. Автор проектов стадиона «Казань Арена» и метро.', 
 'Специализируется на «зелёном» строительстве. Студенты побеждают в международных архитектурных конкурсах.',
 'https://www.kgasu.ru/applicant/'),
('Казанский государственный аграрный университет', 
 'КГАУ',
 'https://tatarstan.ru/file/news/681_n2163553_big.jpg',
 'https://cdn.culture.ru/images/93a2c73a-1311-576b-a27f-42af9ddcc3df',
 'Основан в 1922 году. 3000 га опытных полей. Готовит агрономов, ветеринаров и биоинженеров с использованием дронов.', 
 'Внедряет AI для анализа урожая. Партнёр сельхозпредприятий Татарстана и Европы.',
 'https://priem.kazgau.ru'),
('Казанский инновационный университет имени В.Г. Тимирясова',
 'КИУ',
 'https://cdn.culture.ru/images/fe87788b-7b31-52ff-845a-d1834a03da5b',
 'https://avatars.dzeninfra.ru/get-zen_doc/3557661/pub_602da27d5f462a3bfd7d94c3_602da664ffa2d86ae45aa02b/scale_1200',
 'Первый негосударственный вуз Татарстана (1994 г.). Акцент на IT, цифровой экономике и стартапах. 70+ бизнес-инкубаторов.', 
 'Выпускники создали 200+ технологических компаний. Курсы по блокчейну и AI.',
 'https://ieml.ru/priemnaya-komissiya/postuplenie/'),
('Казанский государственный институт культуры',
 'КГИК',
 'https://s0.rbk.ru/v6_top_pics/media/img/3/39/754356690088393.jpeg',
 'https://picture.portalbilet.ru/origin/2cc95307-d5c1-4b60-a924-d2f9609b7034.jpeg',
 'Центр творческого образования с 1969 года. Факультеты: дизайн, музыка, театр и медиа. Организует фестиваль «Созвездие-Йолдызлык».', 
 'Студенческие коллективы гастролируют в 20+ странах. Музей национальных инструментов.',
 'https://kazgik.ru/abitur/'),
('Казанский юридический институт МВД России',
 'КЮИ МВД',
 'https://static.mvd.ru/upload/site136/document_images/3(61)-800x600.jpg',
 'https://www.susu.ru/sites/default/files/field/image/1_347.jpg',
 'Готовит экспертов по кибербезопасности и криминалистике с 1976 года. Полигон для цифровых расследований.', 
 'Спецкурсы по борьбе с хакерами. 95% выпускников — в МВД, ФСБ и корпоративной защите.',
 'https://кюи.мвд.рф/Postuplenie/ответы-на-часто-задаваемые-вопросы-связа');

INSERT INTO moscow_unis (name, short_name, article1, article2, img1, img2, url) 
VALUES 
('Московский государственный университет имени М.В. Ломоносова', 'МГУ',
'Основан в 1755 году. Старейший и самый престижный вуз России. 39 факультетов, 15 НИИ, собственная научная библиотека с 9 млн книг.',
'Включает знаменитые "Ломоносовские" корпуса на Воробьёвых горах. 11 нобелевских лауреатов среди выпускников и преподавателей.',
'https://cdn.culture.ru/images/7b2b6db0-dbd0-59fc-bfec-052d74040332',
'https://cs8.pikabu.ru/post_img/2017/04/12/0/og_og_1491944463224220086.jpg',
'https://cpk.msu.ru'),
('Московский физико-технический институт', 'МФТИ',
'Основан в 1946 году. Кузница кадров для космической и IT-отраслей. Система "Физтеха" включает базовые кафедры в 90+ научных центрах.',
'Выпускники создали "Яндекс", ABBYY и другие tech-компании. 100% студентов участвуют в реальных научных проектах.',
'https://habrastorage.org/getpro/habr/upload_files/20f/4b9/8d2/20f4b98d2c254f600eff7f4cc2fa7b90.jpeg',
'https://habrastorage.org/webt/36/xp/ao/36xpaoq6_t7x5b_ogbjaknbffv0.jpeg',
'https://mipt.ru/applicants'),
('Национальный исследовательский университет "Высшая школа экономики"', 'НИУ ВШЭ',
'Создан в 1992 году. Лидер в экономике и социальных науках. 4 кампуса в России, международные программы на английском.',
'Пионер цифрового образования: 150+ онлайн-курсов. Рейтинг QS: топ-100 мировых вузов по экономике.',
'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/HSE_University.jpg/1599px-HSE_University.jpg',
'https://avatars.mds.yandex.net/i?id=6a19fc17b319496e9c41399d6949b10e_l-5219934-images-thumbs&n=13',
'https://ma.hse.ru/earlyinvitation?utm_source=yandex&utm_medium=cpc&utm_campaign=hse&utm_term=earlyinvitation&utm_content=mk&yclid=13936100634134839295'),
('Московский государственный технический университет имени Н.Э. Баумана', 'МГТУ',
'Основан в 1830 году. Флагман инженерного образования. Специализации: робототехника, космические системы, биомедицина.',
'Партнёр Роскосмоса и Росатома. 85% выпускников работают в оборонно-промышленном комплексе.',
'https://s11.stc.all.kpcdn.net/russia/wp-content/uploads/2022/02/Glavnyj_uchebnyj_korpus-MGTU.jpg',
'https://storage.myseldon.com/news-pict-18/18EF872AE6909E95DF265D041E5B9595',
'https://bmstu.ru/admission'),
('Российский университет дружбы народов', 'РУДН',
'Основан в 1960 году. 150 стран представляют 25 тыс. студентов. 500+ программ, включая медицину и агротехнологии.',
'Единственный вуз с кафедрой ЮНЕСКО. Языки обучения: русский, английский, французский, испанский.',
'https://eng.rudn.ru/u/www/images/news/krest2018-ph-21.png',
'https://torg.spb.ru/torgimages2/aHR0cHM6Ly93d3cudG9wbmV3cy5ydS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8xMS9SWUROLmpwZ0lNR0Q1ODgzMjc1',
'https://www.rudn.ru/admissions/admission-for-foreign-citizens/admission-rules'),
('Национальный исследовательский ядерный университет "МИФИ"', 'МИФИ',
'Создан в 1942 году для атомного проекта. Ведущий центр ядерной физики, кибербезопасности и нанотехнологий.',
'Имеет исследовательский реактор. Сотрудничает с CERN и Росатомом. 70% выпускников — в наукоёмких отраслях.',
'https://mephi.ru/content/public/images/gallery/2134649523/1.jpg',
'https://vogazeta.ru/uploads/full_size_1625208419-498fb11d7e738c9f53e8fc9d72a18ed8.jpg',
'https://mephi.ru/abitur'),
('Московский государственный институт международных отношений', 'МГИМО',
'Основан в 1944 году. Элитный вуз для дипломатов и политологов. 53 языка преподавания, включая редкие восточные.',
'Выпускники работают в ООН, МИД и международных корпорациях. Библиотека содержит 700 тыс. книг на 62 языках.',
'https://stihi.ru/pics/2018/03/28/2185.jpg',
'https://cdn.forbes.ru/files/presets/1920_800/gallery_images/mgimo_main_panorama.jpg__1561556095__71269__vid525155e.jpg',
'https://mgimo.ru/abitur/?utm_source=yandex.ru&utm_medium=organic&utm_campaign=yandex.ru&utm_referrer=yandex.ru'),
('Российская академия народного хозяйства и государственной службы', 'РАНХиГС',
'Создана в 2010 году. Главный вуз для госслужащих и управленцев. 54 филиала по России, MBA-программы с Harvard.',
'Центр подготовки топ-менеджеров. Ежегодные стажировки в Правительстве РФ и крупных компаниях.',
'https://i.vuzopedia.ru/storage/app/uploads/public/59d/a33/fb8/59da33fb89d6f888565822.jpg',
'https://avatars.mds.yandex.net/get-altay/5587495/2a0000017e69506eb2a88a600a86dd4f5d9d/XXL_height',
'https://www.ranepa.ru/bakalavriat/'),
('Московский авиационный институт', 'МАИ',
'Основан в 1930 году. Ключевой вуз авиакосмической отрасли. Собственные КБ, аэродром и центр 3D-печати деталей для самолётов.',
'Партнёр Boeing, Airbus и "Сухого". 80% студентов трудоустраиваются до выпуска.',
'https://mai.ru/upload/iblock/b8f/mmw6plggrg05vj1g1ztqt3gzys5zvssr/mai1.jpg',
'https://scientificrussia.ru/images/z/2g8z-full.jpg',
'https://priem.mai.ru'),
('Российский экономический университет имени Г.В. Плеханова', 'РЭУ',
'Основан в 1907 году. Старейшая бизнес-школа России. Программы по финансам, маркетингу и цифровой экономике.',
'Аккредитация ACCA и CIMA. Выпускники руководят Сбербанком, ВТБ и другими крупными компаниями.',
'https://proverili.ru/uploads/media/247/22.jpg',
'https://cdni-vm.servicecdn.ru/2022.01/original/1200_61f3f11b82682c74ca683777.jpg',
'https://www.rea.ru/pk/entrant/bakalavriat-i-spetsialitet');

INSERT INTO stp_unis (name, short_name, article1, article2, img1, img2, url) 
VALUES 
('Санкт-Петербургский государственный университет', 'СПбГУ',
'Основан в 1724 году Петром I. Старейший вуз России. 24 факультета, включая уникальные программы по арктическим исследованиям и когнитивным наукам.',
'Включает знаменитый Двенадцатиколлегиум. 9 нобелевских лауреатов. Библиотека насчитывает 7 млн томов, включая рукописи XVIII века.',
'https://alrf.ru/upload/resize_cache/iblock/561/1005_580_2/SP_GU6.jpg',
'https://avatars.dzeninfra.ru/get-zen_doc/9716076/pub_6470842d6b0870593a447265_64771188740cf83316ee6b55/scale_1200',
'https://spbu.ru/postupayushchim'),
('Национальный исследовательский университет ИТМО', 'ИТМО',
'Ведущий вуз в области фотоники, квантовых технологий и компьютерных наук. 7 раз побеждал в чемпионате мира по программированию (ACM ICPC).',
'Центр НТИ по квантовым коммуникациям. Студенческие стартапы привлекают $10+ млн инвестиций ежегодно.',
'https://planarchel.ru/upload/medialibrary/046/o2zj783rspot5avvxpvcdwg5womghzen/itmo2.jpg',
'https://habrastorage.org/getpro/habr/upload_files/e0a/069/dd2/e0a069dd27008b5e2fe1dca57bb5ccb5.jpg',
'https://abit.itmo.ru'),
('Санкт-Петербургский политехнический университет Петра Великого', 'Политех',
'Основан в 1899 году. Флагман инженерного образования. 15 институтов, включая передовые центры по ядерной энергетике и робототехнике.',
'Партнёр Siemens и Tesla. Кампус включает технопарк с 150 инновационными компаниями.',
'https://avatars.mds.yandex.net/get-altay/11444509/2a0000018ea3b4f1f798046a8e2b197a4075/XXXL',
'https://avatars.mds.yandex.net/i?id=1c9b1fe0aae08720d74c43fa72d6953e_l-5235999-images-thumbs&n=13',
'https://www.spbstu.ru/abit/bachelor/'),
('Российский государственный педагогический университет им. А.И. Герцена', 'РГПУ',
'Крупнейший педагогический вуз России с 1797 года. 20 факультетов, включая редкие программы по инклюзивному образованию.',
'Разрабатывает федеральные образовательные стандарты. Выпускники преподают в 40+ странах мира.',
'https://www.herzen.spb.ru/upload/medialibrary/a06/w1c0rxkl4dnipjt70z7zh6m3z50mnqel/DSC_3519-_-kopiya.JPG',
'https://i01.fotocdn.net/s106/9e02c811e2406ad2/public_pin_l/2303680447.jpg',
'https://www.herzen.spb.ru/abiturients/'),
('Санкт-Петербургский горный университет', 'Горный',
'Первое высшее техническое учебное заведение России (1773 г.). Готовит специалистов для нефтегазовой и горнодобывающей отраслей.',
'Имеет собственный музей минералогии с 240 тыс. экспонатов. Партнёр "Газпрома" и "Норникеля".',
'https://www.rogtecmagazine.com/wp-content/uploads/2023/05/spb-gornii-universitet-smapse.jpg',
'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_65dce8d8900713509a44ac90_65dce928d2b1603f98c7460d/scale_1200',
'https://priem.spmi.ru'),
('Санкт-Петербургский государственный электротехнический университет', 'ЛЭТИ',
'Пионер электротехнического образования с 1886 года. Специализации: телекоммуникации, биомедицинская инженерия, IoT.',
'Разработал первую в России систему беспроводной передачи энергии. Базовые кафедры в "Ростехе" и "Сколково".',
'https://avatars.mds.yandex.net/i?id=86954eaefb733214dcb3bf8911c7b8e3_l-5869826-images-thumbs&n=13',
'https://www.atomic-energy.ru/files/styles/figure_center/public/images/2024/05/img_5787-hdr-panorama1.jpg',
'https://abit.etu.ru'),
('Санкт-Петербургский государственный морской технический университет', 'СПбГМТУ',
'Ведущий вуз судостроения с 1930 года. Участвует в создании атомных ледоколов и подводных аппаратов для Арктики.',
'Экспериментальный бассейн для тестирования судов — крупнейший в Европе. Партнёр "Объединённой судостроительной корпорации".',
'https://images.fooby.ru/1/18/6/852892',
'https://postupi.info/files/uniph/233_9.jpg',
'https://www.smtu.ru/ru/page/707/'),
('Санкт-Петербургский государственный университет аэрокосмического приборостроения', 'ГУАП',
'Специализируется на авионике и космических системах управления с 1941 года. Центр разработки дронов и спутниковых технологий.',
'Сотрудничает с "Роскосмосом" и Airbus. 80% выпускников работают в оборонно-космическом комплексе.',
'https://avatars.dzeninfra.ru/get-zen_doc/1909059/pub_60a8075e706b5c563165fb5f_60a81462b9ff4e00de6c3bde/scale_1200',
'https://cdnstatic.rg.ru/uploads/images/2022/11/08/foto-guap-1_8a2.jpeg',
'https://priem.guap.ru'),
('Санкт-Петербургский государственный экономический университет', 'СПбГЭУ',
'Основан в 2012 году через слияние трёх вузов. Ведущий центр подготовки финансистов и аналитиков для Северо-Западного региона.',
'Аккредитация ACCA. Программы двойных дипломов с университетами Германии и Франции.',
'https://unecon.ru/wp-content/uploads/2014/05/img_0146.jpg',
'https://unecon.ru/wp-content/uploads/2024/02/zdanie.jpg',
'https://unecon.ru/priem/'),
('Санкт-Петербургская государственная художественно-промышленная академия им. А.Л. Штиглица', 'Академия Штиглица',
'Основана в 1876 году. Кузница кадров для искусства и дизайна. Факультеты: стекло, керамика, текстиль, мебель, графический дизайн.',
'Музей прикладного искусства с коллекцией из 35 тыс. предметов. Выпускники работают в Эрмитаже и ведущих дизайн-бюро Европы.',
'https://cdn.10nauki.ru/upload/iblock/91f/w93had39jydr3jmw166ssso2fx87ffqu/141.jpg',
'https://avatars.mds.yandex.net/get-altay/1547687/2a0000016b8c6661b10dd5f126dad20650bb/XXXL',
'https://www.ghpa.ru/abiturient');